#:schema node_modules/wrangler/config-schema.json

name = "yukio-api"
main = "src/index.ts"
compatibility_date = "2026-10-08"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "yukio-ratings-db"
database_id = "84b22e1e-29ae-437c-b7ec-63337c7387d1"
migrations_dir = "migrations"

[ai]
binding = "AI"

[observability]
enabled = true

[vars]
YUKIONIME_API = "https://yukionime.pages.dev/api/v1/anime.json"
YUKIO_DATA_REPO = "bimaakbar-dev/yukio-data"
YUKIO_DATA_BRANCH = "main"

BATCH_SIZE = "8"


INCREMENTAL = "true"
SCRAPE_TTL_DAYS = "30"

[dev]
port = 8787
local_protocol = "http"