#:schema node_modules/wrangler/config-schema.json

name = "yukio-api"
main = "src/index.ts"
compatibility_date = "2026-10-08"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "yukio-ratings-db"
database_id = "84b22e1e-29ae-437c-b7ec-63337c7387d1"
# preview_database_id = "REPLACE_WITH_YOUR_PREVIEW_DATABASE_ID"
migrations_dir = "migrations"

[observability]
enabled = true

[vars]
ALLOWED_ORIGINS = "https://yukionime.pages.dev,http://localhost:4321"

[dev]
port = 8787
local_protocol = "http"